### ISSUE TITLE
Endless Stairwell repl doesn't work anymore

### ISSUE THREAD

**Issue by plasma4** [Reinhardt-C/Incremental-Limits#43]
Updated link [here](https://gsui5051.github.io/Endless-Stairwell/Endless-Stairwell.html)

**Comment by Hexagon1296** [comment]
Yeah, we all know how stupid of an idea it was for Replit to straight up f*cking kill repl.co, even I was affected to the extent that [Incremental Universe Growth](https://hexagon1296.github.io/Incremental-Universe-Growth)'s original creator is unrecognizable from the repository page because the creator, -Danielt-, is only twelve.

**Comment by ImmediateMurderProfessionals** [comment]
> Yeah, we all know how stupid of an idea it was for Replit to straight up f*cking kill repl.co, even I was affected to the extent that [Incremental Universe Growth](https://hexagon1296.github.io/Incremental-Universe-Growth)'s original creator is unrecognizable from the repository page because the creator, -Danielt-, is only twelve.

What is so bad about Danielt being "only 12"? You're also 12.

**Comment by Hexagon1296** [comment]
@Reinhardt-C Just lock the thread. I created a pull request.

**Comment by ImmediateMurderProfessionals** [comment]
> @Reinhardt-C Just lock the thread. I created a pull request.

Yeah, I feel it would be a good idea to lock the thread and accept the pull request.

**Comment by Reinhardt-C** [comment]
> > Yeah, we all know how stupid of an idea it was for Replit to straight up f*cking kill repl.co, even I was affected to the extent that [Incremental Universe Growth](https://hexagon1296.github.io/Incremental-Universe-Growth)'s original creator is unrecognizable from the repository page because the creator, -Danielt-, is only twelve.
> 
> What is so bad about Danielt being "only 12"? You're also 12.

Using either github or replit as a 12 year old violates the terms of service of either site. I strongly recommend you drop the topic.

**Comment by ImmediateMurderProfessionals** [comment]
> > > Yeah, we all know how stupid of an idea it was for Replit to straight up f*cking kill repl.co, even I was affected to the extent that [Incremental Universe Growth](https://hexagon1296.github.io/Incremental-Universe-Growth)'s original creator is unrecognizable from the repository page because the creator, -Danielt-, is only twelve.
> > 
> > 
> > What is so bad about Danielt being "only 12"? You're also 12.
> 
> Using either github or replit as a 12 year old violates the terms of service of either site. I strongly recommend you drop the topic.

That’s why I’m glad I didn’t start using replit until july 2023 (a bit more than three months after i turned 13) and github six months later when repl.co domains were killed

**Comment by Hexagon1296** [comment]
> > > Yeah, we all know how stupid of an idea it was for Replit to straight up f*cking kill repl.co, even I was affected to the extent that [Incremental Universe Growth](https://hexagon1296.github.io/Incremental-Universe-Growth)'s original creator is unrecognizable from the repository page because the creator, -Danielt-, is only twelve.
> > 
> > 
> > What is so bad about Danielt being "only 12"? You're also 12.
> 
> Using either github or replit as a 12 year old violates the terms of service of either site. I strongly recommend you drop the topic.

BTW: -Danielt- joined Replit **4** years ago for The Coder School, and Replit ToS does state an exception for education.

**Comment by plasma4** [comment]
Let's drop this: the issue is already closed

**Comment by ImmediateMurderProfessionals** [comment]
> > > > Yeah, we all know how stupid of an idea it was for Replit to straight up f*cking kill repl.co, even I was affected to the extent that [Incremental Universe Growth](https://hexagon1296.github.io/Incremental-Universe-Growth)'s original creator is unrecognizable from the repository page because the creator, -Danielt-, is only twelve.
> > > 
> > > 
> > > What is so bad about Danielt being "only 12"? You're also 12.
> > 
> > 
> > Using either github or replit as a 12 year old violates the terms of service of either site. I strongly recommend you drop the topic.
> 
> BTW: -Danielt- joined Replit **4** years ago for The Coder School, and Replit ToS does state an exception for education.

Did you join for educational purposes?
