### ISSUE TITLE
Do NOT add IUG

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [Reinhardt-C/Incremental-Limits#53]
IUG was made by an underage GitHub user, and it would be a bad idea to endorse being on Github before you turn 13. Also, IUG contains insults towards me, calling me a "filthy liar who has said some of the worst things imagineable [sic]", even though I am just a perfectly fine autistic 14 year old boy who is trying to get creator points in Geometry Dash.

**Comment by mush298** [comment]
link?

**Comment by ImmediateMurderProfessionals** [comment]
IUG can be found at https://hexagon1296.github.io/Incremental-Universe-Growth/

@Hexagon1296, who made IUG, recently made a pull request which added IUG's limit (it hasn't been merged afaik)

**Comment by ImmediateMurderProfessionals** [comment]
Screenshot of the insults on IUG (That BombCraft guy in question is me btw)

![IMG_7864](https://github.com/Reinhardt-C/Incremental-Limits/assets/156855194/33d97235-d290-4704-a4d5-8443ca7e3f6a)

**Comment by ImmediateMurderProfessionals** [comment]
UPDATE: IUG no longer has those insults but it's still made by an underage user LOL

**Comment by ImmediateMurderProfessionals** [comment]
UPDATE 2: IUG is removed because the creator is banned
